version: "3.5"

services:
    ### Frontend Server #########################################
    frontend:
        build:
            context: .
            args:
                - NODE_VERSION=${ENV_NODE_VERSION}
        volumes:
            - ${ENV_APP_CODE_PATH_HOST}:${ENV_APP_CODE_PATH_CONTAINER}${ENV_APP_CODE_CONTAINER_FLAG}
        ports:
            - "${ENV_NGINX_HOST_HTTP_PORT}:80"
